### ISSUE TITLE
cant build PHP 8.2.0 with mcrypt 1.0.5

### ISSUE THREAD

**Issue by cyrax13** [php/pecl-encryption-mcrypt#12]
Hello there)

One year later, new php version - problem is the same https://github.com/php/pecl-encryption-mcrypt/issues/8 )

Simply try to build docker image for release version of PHP 8.2.0 using alpine linux 3.16 (`8.2.0-fpm-alpine3.16`), source code from here: https://github.com/docker-library/php/blob/cc901e9594f79c305d9508e5b5df572eb93245b4/8.2/alpine3.16/fpm/Dockerfile

In my Dockerfile:
```
RUN pecl install mcrypt
```
Results - build failed:
```
WARNING: channel "pecl.php.net" has updated its protocols, use "pecl channel-update pecl.php.net" to update
pecl/mcrypt is not compatible with PHP version 8.2.0
No valid packages found
install failed
```
Maybe it is worth increasing the version range in the file [package.xml](https://github.com/php/pecl-encryption-mcrypt/blob/master/package.xml)
```
<max>8.2.0</max>
<exclude>8.2.0</exclude>
```
to 8.3.0?

Can you fix this issue again? Thanks)

PS i did it on a test environment, changed the version to 8.3.0 in the xml file, PHP was built successfully)

**Comment by micperr** [comment]
I have the same problem that is I cannot compile mcrypt-1.0.5 with PHP 8.2.0 on `php:8.2.0-fpm` docker image. Adding `-n` flag to `pecl install` helps but I am afraid of unexpected consuequences of that.

However I am getting a different error:

```
error: 'mcrypt' does not exist

usage: /usr/local/bin/docker-php-ext-enable [options] module-name [module-name ...]
   ie: /usr/local/bin/docker-php-ext-enable gd mysqli
       /usr/local/bin/docker-php-ext-enable pdo pdo_mysql
       /usr/local/bin/docker-php-ext-enable --ini-name 0-apc.ini apcu apc

Possible values for module-name:
amqp.so bcmath.so exif.so gd.so intl.so opcache.so pdo.so pdo_pgsql.so pgsql.so sodium.so xdebug.so xml.so zip.so
```

**Comment by ishu202** [comment]
for now I fixed it by bumping down the php version to 8.1 may be stability is the issue they don't have it pre-packaged in the aws elastic-beanstalk ? 
https://github.com/aws/elastic-beanstalk-roadmap/issues/214 by the looks of it this just shipped. 
hoping for this to be resolved soon.

**Comment by GM-Alex** [comment]
Could some of the maintainers fix this? As @cyrax13 mentioned it's the same issue like one year ago?

**Comment by rusinov-artem** [comment]
Need help. Same problem

**Comment by pgassmann** [comment]
To those waiting for a fix: Are you sure, you still require this library? In my case, I could just remove the library from our setup.
The library is deprecated for multiple years. https://stackoverflow.com/questions/41272257/mcrypt-is-deprecated-what-is-the-alternative

**Comment by theLine** [comment]
You can try to build it from source.  

So instead of writing this:
```
RUN yes '' | pecl install mcrypt-1.0.5 \
 && echo extension="mcrypt.so" > /usr/local/etc/php/conf.d/php-ext-mcrypt.ini
```

you can write something like this:
```
RUN curl -fsSLOJ https://pecl.php.net/get/mcrypt/1.0.5 \
 && tar -xf mcrypt-1.0.5.tgz
RUN cd mcrypt-1.0.5 \
 && phpize \
 && ./configure \
 && make \
 && make test \
 && cp modules/*.so $(pecl config-get ext_dir) \
 && cd .. \
 && rm -rf mcrypt-1.0.5.tgz mcrypt-1.0.5
RUN echo extension="mcrypt.so" > /usr/local/etc/php/conf.d/php-ext-mcrypt.ini
```

That'll download the `mcrypt` 1.0.5 source files, build it from the source and run the tests.  
After that it'll copy the `mcrypt.so` to the PECL extension directory.

Give it a shot and feel free to modify the snippet to your needs.

**Comment by zeriyoshi** [comment]
#13

**Comment by zeriyoshi** [comment]
Do not use mcrypt for new projects unless you are maintaining an existing project. This library has already done its job. If you do not need it, but a composer dependency requires it, consider using replace.

**Comment by derickr** [comment]
The new 1.0.6 release, that I've just released, fixes this → https://pecl.php.net/package/mcrypt/1.0.6

**Comment by hchautrung** [comment]
Hi all,

I compiled PHP 8.2.11 on Windows 10  but I got stuck with mcrypt 1.0.6. There is no pre-compiled dll from pecl.php.net. So I have tried to install with pecl as below
`pecl install mcrypt-1.0.6`

It shows the error No releases available for package "pecl.php.net/mcrypt" I have updated pecl channel, etc. but the error is still there. I trying to search how to compile mcrypt with php 8.2 or compile mcrypt separately. However, there is not much information to compile in Windows.

I tried to compile php and put mcrypt in ext folder but it shows `configure: error: mcrypt.h not found` during the process. The compiling process is successful but there is no mcrypt because of the error.

Please help because there is a requirement to upgrade our web app to php.8.2 but got stuck with mcrypt

Thank you very much!

**Comment by derickr** [comment]
> I tried to compile php and put mcrypt in ext folder but it shows configure: error: mcrypt.h not found during the process. The compiling process is successful but there is no mcrypt because of the error.

You need to have the "libmcrypt" library available. This has only been compiled with VC14 (https://windows.php.net/downloads/php-sdk/deps/vc14/x86/) and not VC15 or VS16. This means that the last compile that will work, is with PHP **7.1**.

The mcrypt library and extension have been deprecated for 7 years now. You need to replace it with something new, as is explained by @pgassmann 's link to https://stackoverflow.com/questions/41272257/mcrypt-is-deprecated-what-is-the-alternative

**Comment by hchautrung** [comment]
> > I tried to compile php and put mcrypt in ext folder but it shows configure: error: mcrypt.h not found during the process. The compiling process is successful but there is no mcrypt because of the error.
> 
> You need to have the "libmcrypt" library available. This has only been compiled with VC14 (https://windows.php.net/downloads/php-sdk/deps/vc14/x86/) and not VC15 or VS16. This means that the last compile that will work, is with PHP **7.1**.
> 
> The mcrypt library and extension have been deprecated for 7 years now. You need to replace it with something new, as is explained by @pgassmann 's link to https://stackoverflow.com/questions/41272257/mcrypt-is-deprecated-what-is-the-alternative

Hi Derick,

Thanks for your comment. Yes, mcrypt lib has been deprecated for several years. However, our projects still use the one, and currently, we still do maintenance on the projects and there is no timeline to migrate to OpenSSL or Sodium.

As you notice, mrcypt has a new release [1.0.6 ](https://pecl.php.net/package/mcrypt/1.0.6) to make it compatible with php 8.2.x, but there is no pre-compiled version 1.0.6 and I have tried to compile on Windows but still cannot (can be installed or compiled in Linux easily).
